export PATH="/usr/local/bin:/usr/local/php5/bin:$PATH"
export PATH=/usr/local/bin:$PATH
export PATH=$PATH:/opt/local/bin  #Macports
export RAILS_ENV=development

alias firefoxos='Applications/B2G.app/Contents/MacOS/b2g -profile ~/Documents/FirefoxOS/gaia/profile'

# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Enable programmable completion features (you don't need to enable this, if it's
# already enabled in /etc/bash.bashrc and /etc/profile sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then . /etc/bash_completion; fi

# Folders
alias myprojects='cd /Users/jrochelly/Projects/'
alias ATS='cd /Users/jrochelly/Projects/ATS/Sistema\ de\ IPs/Sistema/sip/'

# Sass
alias scss='sass --watch'

# Git
alias ga='git add'
alias gco='git checkout'
alias gc='git commit -m'
alias gb='git branch'
alias gba='git branch -a'
alias gd='git diff'
alias gl='git log'
alias gpl='git pull'
alias gp='git push'
alias gpm='git push origin master'
alias gst='git status'
alias gw='git whatchanged'
alias gr='git rebase'
alias gu='git push origin HEAD --force' #Undo last commit

export PS1="\[\e[0;36m\\w \\$ \[\e[m"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
